version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.collection.enabled=true
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  elasticsearch-hq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  cerebro:
    image: lmenezes/cerebro
    ports:
      - "9000:9000"
    environment:
      - CEREBRO_HOST=0.0.0.0
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local
